// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGFLyFeT1Athxjwd6CIki70efDqDGHrWk',
    appId: '1:805378623990:web:1ac8e2c07303660f535fd7',
    messagingSenderId: '805378623990',
    projectId: 'ecommerce-1b0a6',
    authDomain: 'ecommerce-1b0a6.firebaseapp.com',
    storageBucket: 'ecommerce-1b0a6.firebasestorage.app',
    measurementId: 'G-BTC14109WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPOdkZD2u-mrygLUcJLdgdSdlq-1xvnec',
    appId: '1:805378623990:android:a321ffbb54d2b95a535fd7',
    messagingSenderId: '805378623990',
    projectId: 'ecommerce-1b0a6',
    storageBucket: 'ecommerce-1b0a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAii_xRF8Dq_sMxCF2LQojt5pbnk_wAH8',
    appId: '1:805378623990:ios:c297a557bb17338f535fd7',
    messagingSenderId: '805378623990',
    projectId: 'ecommerce-1b0a6',
    storageBucket: 'ecommerce-1b0a6.firebasestorage.app',
    iosClientId: '805378623990-fougotkjdnaqd1uljbcsooa2bt3kp8qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAii_xRF8Dq_sMxCF2LQojt5pbnk_wAH8',
    appId: '1:805378623990:ios:c297a557bb17338f535fd7',
    messagingSenderId: '805378623990',
    projectId: 'ecommerce-1b0a6',
    storageBucket: 'ecommerce-1b0a6.firebasestorage.app',
    iosClientId: '805378623990-fougotkjdnaqd1uljbcsooa2bt3kp8qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGFLyFeT1Athxjwd6CIki70efDqDGHrWk',
    appId: '1:805378623990:web:d3182aea37c471ed535fd7',
    messagingSenderId: '805378623990',
    projectId: 'ecommerce-1b0a6',
    authDomain: 'ecommerce-1b0a6.firebaseapp.com',
    storageBucket: 'ecommerce-1b0a6.firebasestorage.app',
    measurementId: 'G-C5NX5DCWCS',
  );
}
